name = "middleware"
description = ""
version = "0.1.0-dev"

authors = ["lgehu"]
maintainers = ["lgehu <lauric_gehu@etu.u-bourgogne.fr>"]
maintainers-logins = ["lgehu"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
hal = "=0.1.0-dev"

