name = "arm"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["lgehu <lauric_gehu@etu.u-bourgogne.fr>"]
maintainers-logins = ["lgehu"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []


[[depends-on]]
middleware = "=0.1.0-dev"

[[depends-on]]
hal = "=0.1.0-dev"
