name = "f446re_example"
description = ""
version = "0.1.0-dev"

authors = ["lauric"]
maintainers = ["lauric <lauric_gehu@etu.u-bourgogne.fr>"]
maintainers-logins = ["lgehu"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["stm32", "nucleo_f446re"]

executables = ["f446re_example"]

[[depends-on]]
nucleo_f446re = "~0.1.0-dev"

[[pins]]
nucleo_f446re = { path='../nucleo_f446re' }
